### ISSUE TITLE
Como estas?

### ISSUE THREAD

**Issue by mchisnerman3** [bqworks/accordion-slider-jquery#1]
Primero que nada felicitarte por este slider.
Tengo un problema, lo he puesto dentro de un tab en un desarrollo en laravel, pero no se muestra de entrada. Si abro la consola del navegador, aparece, pero sino no.
Que puede ser?

Gracias

**Comment by davidghi** [comment]
Hi,

If the accordion is inside a tab that is initially hidden, the problem would be that it can't calculate its size correctly. If you try to resize the browser it will appear correctly. The solution to this situation is to trigger the 'resize' event when the tab is opened by calling `$('.accordion-slider').accordionSlider('resize');`

If that's not the issue, please provide more details or a link to the page.

Best,
David

**Comment by mchisnerman3** [comment]
Gracias por contestarme. Hice el siguiente codigo
$('#tabs a').on('click', function (e) {
  e.preventDefault()
  x=($(this).attr('id'));

  if (x=="imagenes-tab"){
    $('.accordion-slider').accordionSlider('resize');
  }
})
y sigue sin mostrarlo de entrada, pero, si hago nuevamente click en la pestaña ahi si lo muestra

No se que mas hacer...

**Comment by mchisnerman3** [comment]
Success, i change the code to this:
$('.nav-tabs a').on('shown.bs.tab', function(){
    x=($(this).attr('id'));
       if (x=="imagenes-tab"){
    $('.accordion-slider').accordionSlider('resize');
  }
});
Now is working perfectly!!!
Thanks!

**Comment by davidghi** [comment]
You're welcome! Glad you've worked it out!
